### ISSUE TITLE
loss为inf

### ISSUE THREAD

**Issue by Egrt** [AlbinZhu/yolov7-polygon-detection#4]
您好，我将iou_cuda移植到自己的算法中，在开启cuda时，loss的值在第一个epoch一开始正常下降，但会突然变换为inf,但使用cpu进行训练时，loss的下降时正常的。

**Comment by AlbinZhu** [comment]
iou_cuda是从https://github.com/XinzeLee/PolygonObjectDetection 这个项目抄过来的，建议你去原作者repo提问，个人估计是数据格式的问题，比如你用的box是原尺寸的数字，而不是归一化后的。
