### ISSUE TITLE
How to change your anchors?

### ISSUE THREAD

**Issue by Juddd** [AlbinZhu/yolov7-polygon-detection#5]
I see your cfg/deploy/yolov7.yaml have the anchors:
```
anchors:
  - [12,16, 19,36, 40,28]  # P3/8
  - [36,75, 76,55, 72,146]  # P4/16
  - [142,110, 192,243, 459,401]  # P5/32
```
 But in my task, there are only two targets in my target picture at most, and the area is very large, so I want to change this anchors to a larger size, such as P6/64 and P7/128. How should I change it?

**Comment by AlbinZhu** [comment]
If you want to use p6 then you should use a bigger yolo model, such as cfg/training/yolov7-e6.yaml. and change IAuxDetect to Polygon_Detect.

**Comment by Juddd** [comment]
I mean, I don't need P3/8 and P4/16 anymore, but I don't know how to adjust your anchors in `cfg/training/yolov7-polygon.yaml`:
anchors:
```
  - [12,16, 19,36, 40,28]  # P3/8
  - [36,75, 76,55, 72,146]  # P4/16
  - [142,110, 192,243, 459,401]  # P5/32
```

**Comment by AlbinZhu** [comment]
Try deleting 
 ```
 - [12,16, 19,36, 40,28]  # P3/8
  - [36,75, 76,55, 72,146]  # P4/16
```
and change 
` [[102,103,104], 1, Polygon_Detect, [nc, anchors]],   # Detect(P3, P4, P5)`
to
` [[104], 1, Polygon_Detect, [nc, anchors]],   # Detect(P5)`

**Comment by Juddd** [comment]
Thanks very very much, your method work for me indeed...
